# Generated by Django 3.1.7 on 2021-06-15 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='co2',
            old_name='co2_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='co2',
            old_name='co2_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='co2',
            old_name='co2_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='fertilizer',
            old_name='fertilizer_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='fertilizer',
            old_name='fertilizer_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='humidity',
            old_name='humidity_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='humidity',
            old_name='humidity_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='humidity',
            old_name='humidity_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='led',
            old_name='led_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='led',
            old_name='led_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='led',
            old_name='led_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='temp',
            old_name='temp_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='temp',
            old_name='temp_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='temp',
            old_name='temp_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='waterpump',
            old_name='waterpump_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='waterpump',
            old_name='waterpump_time',
            new_name='time',
        ),
    ]
