# Generated by Django 3.1.7 on 2021-06-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20210615_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='humidity_gnd',
            old_name='humidity_gnd_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='humidity_gnd',
            old_name='humidity_gnd_value',
            new_name='value',
        ),
    ]
